SENDGRID_USERNAME: app40279930@heroku.com
SENDGRID_PASSWORD: ipqh4nhb1236
SECRET_KEY_BASE: dd543f77dc1707bde8c393d31ab7fa8c448ccecd1a414cc89e9b839acf48a47ff99dec2363d04d366b99f4db10668fe93edaf8a18b1751e04a1ac3a366915e40
AWS_ACCESS_KEY_ID: AKIAJYOOIEM252WUUGWQ
AWS_SECRET_ACCESS_KEY: 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
development:
  AWS_BUCKET: bloccitoffproject-development
production:
  AWS_BUCKET: bloccitoffproject-production